name: 'google-chat-notification'
description: 'Google Chat Notification for GitHub Actions'
author: 'Co-qn'
inputs:
  name:
    description: 'job name.'
    required: true
  url:
    description: 'google chat webhook url.'
    required: true
  status:
    description: 'job status.'
    required: true
  customText:
    description: 'Custom text to show in message. Supports HTML tags.'
    required: false
runs:
  using: node12
  main: dist/main.js
branding:
  icon: 'bell'
  color: 'green'