name: 'google-chat-notification'
description: 'Google Chat Notification for GitHub Actions'
author: 'Co-qn'
inputs:
  name:
    description: 'job name.'
    required: true
  url:
    description: 'google chat webhook url.'
    required: true
  status:
    description: 'job status.'
    required: true
  user:
    description: "User who initiated PR"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'