name: "Test"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        uses: ./
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
