---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Google Chat Notification
        uses: ./
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          custom_text: 'This failed because you are bad.'
        if: always()